name: CookieDuel
version: ${version}
main: me.cookie.duel.CookieDuelPlugin
api-version: "1.21"
author: Cookie
softdepend: [PlaceholderAPI]
commands:
  cookieduel:
    description: Main CookieDuel command
    usage: /cookieduel duel <player> | /cookieduel accept [player] | /cookieduel deny [player] | /cookieduel queue | /cookieduel list | /cookieduel random | /cookieduel out
    aliases: [cduel, cd]
permissions:
  cookieduel.admin:
    description: CookieDuel admin commands
    default: op
