name: CookieDuel
version: ${version}
main: me.cookie.duel.CookieDuelPlugin
api-version: "1.21"
author: Cookie
commands:
  cookieduel:
    description: Main CookieDuel command
    usage: /cookieduel queue <id> <mode> | /cookieduel queues
    aliases: [cduel, cd]
permissions:
  cookieduel.admin:
    description: CookieDuel admin commands
    default: op
